/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate OAuth flow with a provider
         * @description Redirects the user to the OAuth provider's authorization page.
         *
         *     **Security measures applied by the server:**
         *     - Generates a cryptographically random `state` parameter (32 bytes, base64url).
         *       Stored server-side (KV with 10-minute TTL) and set in an HttpOnly cookie as backup.
         *       Validated on callback to prevent CSRF.
         *     - Generates a PKCE `code_verifier` (32 bytes, base64url) and derives `code_challenge`
         *       using S256 method. The `code_verifier` is stored server-side; only the `code_challenge`
         *       is sent to the provider. Prevents authorization code interception attacks.
         *     - For Google: also generates a cryptographic `nonce` (32 bytes, base64url) included in
         *       the authorization request and validated against the `id_token` on callback to prevent
         *       token replay attacks.
         *
         *     **Provider-specific authorization URLs:**
         *     - GitHub: `https://github.com/login/oauth/authorize` (GitHub App user authorization)
         *     - Google: `https://accounts.google.com/o/oauth2/v2/auth` (OpenID Connect)
         *     - Discord: `https://discord.com/oauth2/authorize`
         *
         *     **Provider-specific scopes (minimum required):**
         *     - GitHub App: "Email addresses: Read-only" permission (set at app registration, not per-request)
         *     - Google: `openid email profile`
         *     - Discord: `identify email`
         */
        get: operations["oauthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth callback - creates or authenticates user
         * @description Handles the OAuth provider's redirect after user authorization.
         *
         *     **Security checks performed:**
         *     1. Validate `state` parameter against server-side store (constant-time comparison).
         *        Reject if missing, expired (>10 min), or mismatched. Invalidate after use (one-time).
         *     2. Exchange authorization `code` for tokens at the provider's token endpoint using
         *        the stored `code_verifier` (PKCE) and `client_secret`.
         *     3. **Provider-specific identity resolution:**
         *        - GitHub: Call `GET /user` for profile + `GET /user/emails` for verified primary email.
         *          Use numeric `id` as immutable identifier (usernames can change).
         *        - Google: Validate the `id_token` JWT (signature via JWKS, iss, aud, exp, nonce).
         *          Use `sub` claim as immutable identifier. Check `email_verified === true`.
         *        - Discord: Call `GET /users/@me` for profile. Use snowflake `id` as immutable identifier.
         *          Check `verified === true` before trusting email.
         *     4. **Email verification gate:** Only trust provider emails where the provider confirms
         *        verification. Unverified emails are never used for account matching (prevents
         *        account takeover via unverified email registration on the provider).
         *     5. **Account matching:** Match by `(provider, provider_user_id)`. If no match but a
         *        verified email matches an existing user, create a `PendingLink` for manual approval
         *        (never auto-merge by email).
         *     6. **Session fixation prevention:** Always create a new session after successful
         *        authentication. Invalidate any pre-authentication session. Never reuse session IDs.
         *
         *     **Token endpoint Content-Type:** Discord requires `application/x-www-form-urlencoded`
         *     (not JSON). GitHub and Google accept both but form-urlencoded is standard.
         *
         *     **Response headers for defense in depth:**
         *     - `Referrer-Policy: no-referrer` — prevents authorization code leakage via Referer header.
         *     - `Cache-Control: no-store` — prevents caching of authentication responses.
         *
         *     On first-time user creation, the response includes `api_key` (shown only once).
         *     The API key is stored as a SHA-256 hash in the database; the plaintext is not recoverable.
         */
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link additional OAuth provider to current account
         * @description Initiates an OAuth flow to link a new provider to the authenticated user's account.
         *     The user must already be logged in (session cookie required).
         *
         *     Same PKCE and state security measures as the initial OAuth flow (/auth/{provider}).
         *     On callback, the provider is linked to the current session's user (identity is
         *     already established), which is safer than email-based auto-linking.
         */
        post: operations["oauthLinkStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth link callback - links provider to current account
         * @description Handles the OAuth callback for account linking. The user must be authenticated
         *     (session cookie sent via SameSite=Lax on the cross-site redirect).
         *
         *     **Security checks:**
         *     - Validates state and PKCE code_verifier (same as login callback).
         *     - Verifies the provider's email is marked as verified before storing.
         *     - If the provider account is already linked to a different user, returns 409 Conflict.
         *
         *     Uses `Referrer-Policy: no-referrer` and `Cache-Control: no-store` headers.
         */
        get: operations["oauthLinkCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/approve/{pending_link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve merging an OAuth account into existing user
         * @description Approves a pending account link created when an OAuth login's verified email
         *     matched an existing account. The user must be authenticated as the owner of
         *     the existing account.
         *
         *     Pending links expire after 1 hour (410 Gone if expired).
         *     On approval, the OAuth provider is linked to the existing account and the
         *     pending link record is deleted.
         */
        post: operations["approvePendingLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OAuth providers linked to current account */
        get: operations["getLinkedProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink an OAuth provider from current account */
        delete: operations["unlinkProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current session info
         * @description Returns the current user and linked OAuth providers for the authenticated session.
         *
         *     **Session lifecycle:**
         *     - Sliding expiration: 24 hours of inactivity invalidates the session.
         *       `last_active_at` is updated at most once per 5 minutes to reduce D1 writes.
         *     - Absolute expiration: sessions expire 7 days after creation regardless of activity.
         *     - Sessions are stored as SHA-256 hashes in D1; the raw token never leaves the client cookie.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /**
         * Logout - invalidate current session
         * @description Deletes the session from the database and clears the session cookie.
         *     Both steps are required: cookie deletion alone leaves a valid session in the DB,
         *     and DB deletion alone leaves a cookie traveling on the wire.
         */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate API key
         * @description Generates a new API key, immediately invalidating the old one.
         *     The new key is the only value returned; it cannot be retrieved again.
         *
         *     **Security measures:**
         *     - New key: 32 bytes of cryptographic randomness, base64url-encoded, prefixed with `ck_`.
         *       The `ck_` prefix enables secret scanning in Git repositories.
         *     - Storage: only the SHA-256 hash of the key is stored in the database.
         *     - KV cache: the old key's cache entry is explicitly deleted (not relying on TTL expiry).
         *     - All other active sessions for this user are invalidated (forces re-authentication
         *       on other devices to prevent use of a potentially compromised key).
         *
         *     **Response includes `Cache-Control: no-store`** to prevent the key from being cached.
         */
        post: operations["regenerateApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active sessions
         * @description Returns all active sessions for the current user, including the current session
         *     (marked with `is_current: true`). Never exposes `token_hash` in the response.
         *
         *     Useful for "manage active sessions" UI to let users see and revoke
         *     sessions on other devices.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        /**
         * Revoke all other sessions
         * @description Invalidates all sessions for the current user except the one making the request.
         *     Useful as a "sign out everywhere else" feature.
         *
         *     Also triggered automatically on API key regeneration and credential changes.
         */
        delete: operations["revokeAllOtherSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a specific session
         * @description Invalidates a specific session by ID. The session must belong to the authenticated user.
         *     If the user revokes their current session, the session cookie is also cleared
         *     (effectively a logout).
         */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's profile */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user's profile */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/users/current/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's projects */
        get: operations["getProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/data_dumps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List data exports */
        get: operations["getDataDumps"];
        put?: never;
        /** Start a data export */
        post: operations["createDataDump"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/heartbeats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List heartbeats for a given day */
        get: operations["getHeartbeats"];
        put?: never;
        /** Create a single heartbeat */
        post: operations["createHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/heartbeats.bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create up to 25 heartbeats at once */
        post: operations["createHeartbeatsBulk"];
        /** Delete heartbeats */
        delete: operations["deleteHeartbeatsBulk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coding activity summaries for a date range */
        get: operations["getSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/stats/{range}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coding statistics for a time range */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/status_bar/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today's coding activity for IDE status bars
         * @description Cached version of summaries for today. Returns a summary with zero values while cache is being populated.
         */
        get: operations["getStatusBarToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/all_time_since_today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total coding time since account creation */
        get: operations["getAllTimeSinceToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/durations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coding durations for a day (heartbeats joined by timeout) */
        get: operations["getDurations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's goals */
        get: operations["getGoals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single goal with chart data */
        get: operations["getGoal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public leaderboard ranked by coding activity */
        get: operations["getPublicLeaders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/leaderboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User's private leaderboards */
        get: operations["getPrivateLeaderboards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/leaderboards/{board_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rankings in a specific private leaderboard */
        get: operations["getPrivateLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/insights/{insight_type}/{range}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coding activity insights */
        get: operations["getInsight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/custom_rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's custom rules */
        get: operations["getCustomRules"];
        /** Replace user's custom rules */
        put: operations["updateCustomRules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/custom_rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a custom rule */
        delete: operations["deleteCustomRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/machine_names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's machines */
        get: operations["getMachineNames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/user_agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List editor plugins that have sent data */
        get: operations["getUserAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/external_durations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List external durations for a day */
        get: operations["getExternalDurations"];
        put?: never;
        /** Create a single external duration */
        post: operations["createExternalDuration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/external_durations.bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create up to 100 external durations */
        post: operations["createExternalDurationsBulk"];
        /** Delete external durations */
        delete: operations["deleteExternalDurationsBulk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/projects/{project}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commits for a project with coding time */
        get: operations["getProjectCommits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/projects/{project}/commits/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single commit with coding time */
        get: operations["getProjectCommit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's organizations */
        get: operations["getOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/orgs/{org_id}/dashboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization dashboards */
        get: operations["getOrgDashboards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/orgs/{org_id}/dashboards/{dashboard_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dashboard members */
        get: operations["getOrgDashboardMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/orgs/{org_id}/dashboards/{dashboard_id}/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organization dashboard coding summaries */
        get: operations["getOrgDashboardSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all known editors */
        get: operations["getEditors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program_languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all known programming languages */
        get: operations["getProgramLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server metadata */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/{range}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate stats of all users */
        get: operations["getGlobalStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        OAuthProvider: "github" | "google" | "discord";
        User: {
            id: string;
            username: string;
            display_name?: string;
            /** Format: email */
            email?: string;
            /** Format: uri */
            photo?: string;
            bio?: string;
            city?: string;
            timezone?: string;
            /** Format: date-time */
            last_heartbeat_at?: string;
            last_project?: string;
            /** @enum {string} */
            plan?: "free" | "basic" | "premium";
            /** @description Keystroke timeout in minutes */
            timeout?: number;
            is_hireable?: boolean;
            github_username?: string;
            twitter_username?: string;
            /** Format: uri */
            website?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
        };
        PendingLink: {
            id: string;
            provider: components["schemas"]["OAuthProvider"];
            provider_username: string;
            /** Format: email */
            provider_email: string;
            /** @description Username of the existing account to merge into */
            existing_username?: string;
            /** Format: date-time */
            expires_at: string;
        };
        LinkedProvider: {
            provider: components["schemas"]["OAuthProvider"];
            /**
             * @description Immutable provider-specific user identifier.
             *     GitHub: numeric id, Google: sub claim, Discord: snowflake id.
             *     Never use email or username as identifier (both are mutable).
             */
            provider_user_id: string;
            provider_username: string;
            /** Format: email */
            provider_email?: string;
            /** @description Whether the provider confirmed the email address is verified */
            email_verified: boolean;
            /** Format: date-time */
            created_at: string;
        };
        Session: {
            id: string;
            /** @description IP address at session creation */
            ip?: string;
            /** @description User-Agent header at session creation */
            user_agent?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_active_at: string;
            /**
             * Format: date-time
             * @description Absolute expiration (7 days from creation)
             */
            expires_at?: string;
            /** @description True if this is the session making the request */
            is_current: boolean;
        };
        Project: {
            id: string;
            name: string;
            /** Format: uri */
            repository?: string;
            /** Format: uri */
            badge?: string;
            color?: string;
            has_public_url?: boolean;
            human_readable_last_heartbeat_at?: string;
            /** Format: date-time */
            last_heartbeat_at?: string;
            human_readable_first_heartbeat_at?: string;
            /** Format: date-time */
            first_heartbeat_at?: string;
            urlencoded_name?: string;
            /** Format: uri */
            url?: string;
            /** Format: date-time */
            created_at?: string;
        };
        DataDump: {
            id: string;
            /** @enum {string} */
            type: "daily" | "heartbeats";
            /** @enum {string} */
            status: "pending" | "processing" | "completed" | "failed";
            /** Format: uri */
            download_url?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        /** @enum {string} */
        Category: "coding" | "building" | "indexing" | "debugging" | "browsing" | "running tests" | "writing tests" | "manual testing" | "writing docs" | "communicating" | "code reviewing" | "notes" | "researching" | "learning" | "designing" | "ai coding";
        HeartbeatInput: {
            /** @description File path, app name, or domain */
            entity: string;
            /** @enum {string} */
            type: "file" | "app" | "domain";
            /**
             * Format: double
             * @description UNIX epoch timestamp
             */
            time: number;
            category?: components["schemas"]["Category"];
            project?: string;
            project_root_count?: number;
            branch?: string;
            language?: string;
            /** @description Comma-separated dependency names */
            dependencies?: string;
            lines?: number;
            ai_line_changes?: number;
            human_line_changes?: number;
            lineno?: number;
            cursorpos?: number;
            is_write?: boolean;
            editor?: string;
            operating_system?: string;
        };
        Heartbeat: components["schemas"]["HeartbeatInput"] & {
            id: string;
            user_id: string;
            machine?: string;
            user_agent_id?: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        SummaryRange: "Today" | "Yesterday" | "Last 7 Days" | "Last 7 Days from Yesterday" | "Last 14 Days" | "Last 30 Days" | "This Week" | "Last Week" | "This Month" | "Last Month";
        GrandTotal: {
            /** Format: double */
            total_seconds: number;
            digital: string;
            text: string;
            hours?: number;
            minutes?: number;
        };
        SummaryItem: {
            name: string;
            /** Format: double */
            total_seconds: number;
            /** Format: double */
            percent: number;
            /** @description Digital clock format (H:MM) */
            digital: string;
            /** @description Human readable (e.g., '2 hrs 30 mins') */
            text: string;
            hours?: number;
            minutes?: number;
            seconds?: number;
        };
        TimeRange: {
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
            /** Format: date */
            date?: string;
            text?: string;
            timezone?: string;
        };
        Summary: {
            grand_total: components["schemas"]["GrandTotal"];
            categories?: components["schemas"]["SummaryItem"][];
            projects?: components["schemas"]["SummaryItem"][];
            languages?: components["schemas"]["SummaryItem"][];
            editors?: components["schemas"]["SummaryItem"][];
            operating_systems?: components["schemas"]["SummaryItem"][];
            dependencies?: components["schemas"]["SummaryItem"][];
            machines?: components["schemas"]["SummaryItem"][];
            branches?: components["schemas"]["SummaryItem"][];
            entities?: components["schemas"]["SummaryItem"][];
            range: components["schemas"]["TimeRange"];
        };
        CumulativeTotal: {
            /** Format: double */
            seconds?: number;
            text?: string;
            digital?: string;
        };
        DailyAverage: {
            /** Format: double */
            seconds?: number;
            text?: string;
        };
        Stats: {
            /** Format: double */
            total_seconds?: number;
            /** Format: double */
            total_seconds_including_other_language?: number;
            /** Format: double */
            daily_average?: number;
            /** Format: double */
            daily_average_including_other_language?: number;
            human_readable_total?: string;
            human_readable_total_including_other_language?: string;
            human_readable_daily_average?: string;
            human_readable_daily_average_including_other_language?: string;
            categories?: components["schemas"]["SummaryItem"][];
            projects?: components["schemas"]["SummaryItem"][];
            languages?: components["schemas"]["SummaryItem"][];
            editors?: components["schemas"]["SummaryItem"][];
            operating_systems?: components["schemas"]["SummaryItem"][];
            dependencies?: components["schemas"]["SummaryItem"][];
            machines?: components["schemas"]["SummaryItem"][];
            best_day?: {
                /** Format: date */
                date?: string;
                /** Format: double */
                total_seconds?: number;
                text?: string;
            };
            range?: components["schemas"]["TimeRange"];
            /** @enum {string} */
            status?: "ok" | "pending_update";
            is_already_updating?: boolean;
            is_up_to_date?: boolean;
        };
        AllTime: {
            /** Format: double */
            total_seconds: number;
            /** @description Human readable (e.g., '1,250 hrs 30 mins') */
            text: string;
            digital: string;
            is_up_to_date: boolean;
            range?: components["schemas"]["TimeRange"];
            project?: string;
        };
        Duration: {
            project: string;
            /**
             * Format: double
             * @description Start time as UNIX epoch
             */
            time: number;
            /**
             * Format: double
             * @description Duration in seconds
             */
            duration: number;
            color?: string;
            entity?: string;
            language?: string;
            branch?: string;
            category?: components["schemas"]["Category"];
            machine?: string;
        };
        Goal: {
            id: string;
            title: string;
            /** @enum {string} */
            type?: "coding" | "languages" | "editors" | "projects";
            /** @enum {string} */
            delta?: "day" | "week";
            /** Format: double */
            target_seconds?: number;
            is_enabled?: boolean;
            is_snoozed?: boolean;
            is_inverse?: boolean;
            languages?: string[];
            editors?: string[];
            projects?: string[];
            chart_data?: {
                /** Format: double */
                actual_seconds?: number;
                /** Format: double */
                goal_seconds?: number;
                range?: components["schemas"]["TimeRange"];
                /** @enum {string} */
                range_status?: "success" | "fail" | "pending";
            }[];
            /** @enum {string} */
            status?: "success" | "fail" | "pending";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
        };
        LeaderboardEntry: {
            rank?: number;
            user?: {
                id?: string;
                display_name?: string;
                username?: string;
                /** Format: uri */
                photo?: string;
                is_hireable?: boolean;
                city?: string;
                country_code?: string;
            };
            running_total?: {
                /** Format: double */
                total_seconds?: number;
                human_readable_total?: string;
                /** Format: double */
                daily_average?: number;
                human_readable_daily_average?: string;
                languages?: {
                    name?: string;
                    /** Format: double */
                    total_seconds?: number;
                }[];
            };
        };
        PrivateLeaderboard: {
            id: string;
            name: string;
            members_count?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
        };
        Insight: {
            type?: string;
            range?: components["schemas"]["TimeRange"];
            days?: {
                /** Format: date */
                date?: string;
                /** Format: double */
                total_seconds?: number;
                text?: string;
            }[];
            best_day?: {
                /** Format: date */
                date?: string;
                /** Format: double */
                total_seconds?: number;
                text?: string;
            };
            daily_average?: {
                /** Format: double */
                seconds?: number;
                text?: string;
            };
            items?: components["schemas"]["SummaryItem"][];
        };
        CustomRule: {
            id: string;
            /** @enum {string} */
            action: "change" | "delete";
            /** @enum {string} */
            source: "project" | "language" | "editor" | "operating_system" | "category" | "entity";
            /** @enum {string} */
            operation: "equals" | "contains" | "starts with" | "ends with";
            source_value: string;
            /** @enum {string} */
            destination: "project" | "language" | "editor" | "operating_system" | "category" | "entity";
            destination_value: string;
            priority?: number;
        };
        CustomRuleInput: {
            /** @description Include to update existing rule */
            id?: string;
            /** @enum {string} */
            action: "change" | "delete";
            /** @enum {string} */
            source: "project" | "language" | "editor" | "operating_system" | "category" | "entity";
            /** @enum {string} */
            operation: "equals" | "contains" | "starts with" | "ends with";
            source_value: string;
            /** @enum {string} */
            destination: "project" | "language" | "editor" | "operating_system" | "category" | "entity";
            destination_value: string;
            priority?: number;
        };
        Machine: {
            id: string;
            /** @description Machine hostname */
            value: string;
            ip?: string;
            /** Format: date-time */
            last_seen_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        UserAgent: {
            id: string;
            /** @description Full user agent string */
            value: string;
            editor?: string;
            version?: string;
            os?: string;
            is_browser_extension?: boolean;
            is_desktop_app?: boolean;
            /** Format: date-time */
            last_seen_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ExternalDurationInput: {
            external_id: string;
            entity: string;
            /** @enum {string} */
            type: "file" | "app" | "domain";
            /** Format: double */
            start_time: number;
            /** Format: double */
            end_time: number;
            category?: components["schemas"]["Category"];
            project?: string;
            branch?: string;
            language?: string;
            meta?: string;
        };
        ExternalDuration: components["schemas"]["ExternalDurationInput"] & {
            id: string;
            user_id: string;
            /** Format: date-time */
            created_at: string;
        };
        Commit: {
            hash: string;
            message: string;
            author_name?: string;
            /** Format: email */
            author_email?: string;
            /** Format: date-time */
            author_date: string;
            committer_name?: string;
            /** Format: email */
            committer_email?: string;
            /** Format: date-time */
            committer_date?: string;
            /** Format: double */
            total_seconds?: number;
            human_readable_total?: string;
            /** Format: uri */
            url?: string;
            ref?: string;
        };
        Organization: {
            id: string;
            name: string;
            timeout?: number;
            timezone?: string;
            writes_only?: boolean;
            /** @enum {string} */
            default_project_privacy?: "visible" | "hidden";
            is_duration_visible?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        OrgDashboard: {
            id: string;
            name: string;
            is_viewing_restricted?: boolean;
            is_manual_time_hidden?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        OrgMember: {
            id: string;
            user: components["schemas"]["User"];
            is_view_only?: boolean;
        };
        Editor: {
            id: string;
            name: string;
            color?: string;
            /** Format: uri */
            website?: string;
            /** Format: uri */
            repository?: string;
            latest_version?: string;
        };
        ProgramLanguage: {
            id: string;
            name: string;
            color?: string;
            is_verified?: boolean;
        };
        GlobalStats: {
            /** Format: double */
            total_seconds?: number;
            /** Format: double */
            total_seconds_including_other_language?: number;
            /** Format: double */
            daily_average?: number;
            human_readable_total?: string;
            human_readable_daily_average?: string;
            categories?: components["schemas"]["SummaryItem"][];
            languages?: components["schemas"]["SummaryItem"][];
            editors?: components["schemas"]["SummaryItem"][];
            operating_systems?: components["schemas"]["SummaryItem"][];
            range?: components["schemas"]["TimeRange"];
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Bad request */
                    error?: string;
                };
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                /** @description Seconds until the rate limit resets */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Too many requests */
                    error?: string;
                };
            };
        };
        /** @description Authentication required or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Unauthorized */
                    error?: string;
                };
            };
        };
        /** @description Resource conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Conflict */
                    error?: string;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Not found */
                    error?: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    oauthRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OAuth provider */
            302: {
                headers: {
                    /**
                     * @description OAuth authorization URL with query parameters: client_id, redirect_uri,
                     *     response_type=code, state, code_challenge, code_challenge_method=S256,
                     *     scope (provider-specific), and nonce (Google only).
                     */
                    Location?: string;
                    /**
                     * @description Short-lived HttpOnly cookie containing the `state` value for CSRF validation
                     *     on callback. Attributes: HttpOnly, Secure, SameSite=Lax, Max-Age=600, Path=/.
                     *     SameSite=Lax is required because the OAuth callback is a cross-site navigation.
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    oauthCallback: {
        parameters: {
            query: {
                /** @description Authorization code from the OAuth provider (one-time use, max 10 min lifetime) */
                code: string;
                /** @description Anti-CSRF state parameter, must match the server-side stored value */
                state: string;
            };
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    /**
                     * @description Session cookie. Attributes: HttpOnly, Secure, SameSite=Lax, Path=/, Max-Age=604800.
                     *     Token is 32 bytes of cryptographic randomness (base64url-encoded).
                     *     Only the SHA-256 hash is stored server-side.
                     */
                    "Set-Cookie"?: string;
                    /** @description Set to `no-referrer` to prevent code leakage */
                    "Referrer-Policy"?: "no-referrer";
                    /** @description Set to `no-store` to prevent caching */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["User"];
                            /**
                             * @description API key for editor plugins (ck_...). Only returned on first-time user creation.
                             *     Stored as SHA-256 hash; this is the only time the plaintext is available.
                             */
                            api_key?: string;
                            is_new_user?: boolean;
                            /**
                             * @description Present when the provider's verified email matches an existing account.
                             *     The user must approve the link via /auth/link/approve/{pending_link_id}
                             *     after authenticating with their existing account. Expires in 1 hour.
                             */
                            pending_link?: components["schemas"]["PendingLink"];
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    oauthLinkStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OAuth provider for linking */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    oauthLinkCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider linked successfully */
            200: {
                headers: {
                    "Referrer-Policy"?: "no-referrer";
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            provider: components["schemas"]["OAuthProvider"];
                            provider_username: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    approvePendingLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pending_link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts merged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["User"];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Pending link expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getLinkedProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of linked providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LinkedProvider"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    unlinkProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider unlinked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    /** @description Set to `no-store` to prevent caching of session data */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["User"];
                            providers?: components["schemas"]["LinkedProvider"][];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated */
            204: {
                headers: {
                    /** @description Clear session cookie (Max-Age=0) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    regenerateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New API key generated */
            200: {
                headers: {
                    /** @description Set to `no-store` to prevent caching */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /**
                             * @description New API key (ck_...). This is the only time the plaintext is available.
                             *     Store it securely; it cannot be retrieved from the server.
                             */
                            api_key: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Session"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeAllOtherSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All other sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username?: string;
                    display_name?: string;
                    bio?: string;
                    city?: string;
                    timezone?: string;
                    timeout?: number;
                    is_hireable?: boolean;
                    github_username?: string;
                    twitter_username?: string;
                    /** Format: uri */
                    website?: string;
                    /** Format: uri */
                    photo?: string;
                };
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getProjects: {
        parameters: {
            query?: {
                /** @description Search term */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDataDumps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of data dumps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DataDump"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDataDump: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "daily" | "heartbeats";
                    /** @default true */
                    email_when_finished?: boolean;
                };
            };
        };
        responses: {
            /** @description Export started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DataDump"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHeartbeats: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of heartbeats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Heartbeat"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatInput"];
            };
        };
        responses: {
            /** @description Heartbeat created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Heartbeat"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createHeartbeatsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatInput"][];
            };
        };
        responses: {
            /** @description Heartbeats accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        responses: [
                            components["schemas"]["Heartbeat"],
                            number
                        ][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteHeartbeatsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    date: string;
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description Heartbeats deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getSummaries: {
        parameters: {
            query?: {
                /** @description Required if range is not provided. Use with end. */
                start?: string;
                /** @description Required if range is not provided. Use with start. */
                end?: string;
                /** @description Predefined range (alternative to start/end). One of start+end or range is required. */
                range?: components["schemas"]["SummaryRange"];
                project?: string;
                /** @description Comma-separated branch names */
                branches?: string;
                /** @description Keystroke timeout in minutes */
                timeout?: number;
                writes_only?: boolean;
                /** @description IANA timezone (e.g. Asia/Tokyo). Shifts the date anchor used for range resolution. Defaults to UTC when omitted. */
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Summary"][];
                        /** Format: date */
                        start?: string;
                        /** Format: date */
                        end?: string;
                        cumulative_total?: components["schemas"]["CumulativeTotal"];
                        daily_average?: components["schemas"]["DailyAverage"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getStats: {
        parameters: {
            query?: {
                timeout?: number;
                writes_only?: boolean;
                /** @description IANA timezone (e.g. Asia/Tokyo). Shifts the date anchor used for range resolution. Defaults to UTC when omitted. */
                timezone?: string;
            };
            header?: never;
            path: {
                range: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Stats"];
                    };
                };
            };
            /** @description Stats are still being calculated */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Stats"];
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getStatusBarToday: {
        parameters: {
            query?: {
                /** @description IANA timezone (e.g. Asia/Tokyo). Determines what "today" means. Defaults to UTC when omitted. */
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Today's status bar data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Summary"];
                        /** Format: date-time */
                        cached_at?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAllTimeSinceToday: {
        parameters: {
            query?: {
                project?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All time data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AllTime"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDurations: {
        parameters: {
            query: {
                date: string;
                project?: string;
                branches?: string;
                timeout?: number;
                writes_only?: boolean;
                timezone?: string;
                slice_by?: "project" | "entity" | "language" | "dependencies" | "operating_system" | "editor" | "category" | "machine";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of durations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Duration"][];
                        branches?: string[];
                        /** Format: date */
                        start?: string;
                        /** Format: date */
                        end?: string;
                        timezone?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of goals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Goal"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal with chart data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Goal"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPublicLeaders: {
        parameters: {
            query?: {
                language?: string;
                is_hireable?: boolean;
                country_code?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard rankings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        current_user?: components["schemas"]["LeaderboardEntry"];
                        data: components["schemas"]["LeaderboardEntry"][];
                        page?: number;
                        total_pages?: number;
                        range?: components["schemas"]["TimeRange"];
                        language?: string;
                        /** Format: date-time */
                        modified_at?: string;
                    };
                };
            };
        };
    };
    getPrivateLeaderboards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of private leaderboards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PrivateLeaderboard"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPrivateLeaderboard: {
        parameters: {
            query?: {
                language?: string;
                country_code?: string;
                page?: number;
            };
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard rankings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LeaderboardEntry"][];
                        page?: number;
                        total_pages?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getInsight: {
        parameters: {
            query?: {
                timeout?: number;
                writes_only?: boolean;
                /** @description Filter for 'days' insight type (0-6 or monday-sunday) */
                weekday?: string;
            };
            header?: never;
            path: {
                insight_type: "weekday" | "days" | "best_day" | "daily_average" | "projects" | "languages" | "editors" | "categories" | "machines" | "operating_systems";
                range: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insight data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Insight"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCustomRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of custom rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CustomRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCustomRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomRuleInput"][];
            };
        };
        responses: {
            /** @description Updated rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CustomRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMachineNames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of machines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Machine"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUserAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserAgent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getExternalDurations: {
        parameters: {
            query: {
                date: string;
                project?: string;
                branches?: string;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of external durations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ExternalDuration"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createExternalDuration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalDurationInput"];
            };
        };
        responses: {
            /** @description External duration created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ExternalDuration"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createExternalDurationsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalDurationInput"][];
            };
        };
        responses: {
            /** @description External durations created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ExternalDuration"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteExternalDurationsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    date: string;
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description External durations deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProjectCommits: {
        parameters: {
            query?: {
                author?: string;
                branch?: string;
                page?: number;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of commits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Commit"][];
                        page?: number;
                        total_pages?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProjectCommit: {
        parameters: {
            query?: {
                branch?: string;
            };
            header?: never;
            path: {
                project: string;
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commit data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Commit"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Organization"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrgDashboards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of dashboards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrgDashboard"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrgDashboardMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrgMember"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrgDashboardSummaries: {
        parameters: {
            query: {
                date: string;
                project?: string;
                branches?: string;
            };
            header?: never;
            path: {
                org_id: string;
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Summary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    getEditors: {
        parameters: {
            query?: {
                unreleased?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of editors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Editor"][];
                    };
                };
            };
        };
    };
    getProgramLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of languages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProgramLanguage"][];
                    };
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ip?: string;
                            version?: string;
                        };
                    };
                };
            };
        };
    };
    getGlobalStats: {
        parameters: {
            query?: {
                /** @description IANA timezone (e.g. Asia/Tokyo). Shifts the date anchor used for range resolution. Defaults to UTC when omitted. */
                timezone?: string;
            };
            header?: never;
            path: {
                range: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GlobalStats"];
                    };
                };
            };
            /** @description Stats are still being calculated */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GlobalStats"];
                        message?: string;
                    };
                };
            };
        };
    };
}
