/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initiate OAuth flow with a provider */
        get: operations["oauthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback - creates or authenticates user */
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link additional OAuth provider to current account */
        post: operations["oauthLinkStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth link callback - links provider to current account */
        get: operations["oauthLinkCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/approve/{pending_link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve merging an OAuth account into existing user */
        post: operations["approvePendingLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OAuth providers linked to current account */
        get: operations["getLinkedProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink an OAuth provider from current account */
        delete: operations["unlinkProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current session info */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Logout - invalidate current session */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate API key */
        post: operations["regenerateApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's profile */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user's profile */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/users/current/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's projects */
        get: operations["getProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/heartbeats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List heartbeats for a given day */
        get: operations["getHeartbeats"];
        put?: never;
        /** Create a single heartbeat */
        post: operations["createHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/heartbeats.bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create up to 25 heartbeats at once */
        post: operations["createHeartbeatsBulk"];
        /** Delete heartbeats */
        delete: operations["deleteHeartbeatsBulk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coding activity summaries for a date range */
        get: operations["getSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/stats/{range}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coding statistics for a time range */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/status_bar/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today's coding activity for IDE status bars
         * @description Cached version of summaries for today. Returns empty summary while cache updates.
         */
        get: operations["getStatusBarToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/all_time_since_today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total coding time since account creation */
        get: operations["getAllTimeSinceToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/durations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coding durations for a day (heartbeats joined by timeout) */
        get: operations["getDurations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's goals */
        get: operations["getGoals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single goal with chart data */
        get: operations["getGoal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public leaderboard ranked by coding activity */
        get: operations["getPublicLeaders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/leaderboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User's private leaderboards */
        get: operations["getPrivateLeaderboards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/leaderboards/{board_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rankings in a specific private leaderboard */
        get: operations["getPrivateLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/insights/{insight_type}/{range}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coding activity insights */
        get: operations["getInsight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/custom_rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's custom rules */
        get: operations["getCustomRules"];
        /** Replace user's custom rules */
        put: operations["updateCustomRules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/custom_rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a custom rule */
        delete: operations["deleteCustomRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/machine_names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's machines */
        get: operations["getMachineNames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/user_agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List editor plugins that have sent data */
        get: operations["getUserAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/external_durations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List external durations for a day */
        get: operations["getExternalDurations"];
        put?: never;
        /** Create a single external duration */
        post: operations["createExternalDuration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/external_durations.bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create up to 100 external durations */
        post: operations["createExternalDurationsBulk"];
        /** Delete external durations */
        delete: operations["deleteExternalDurationsBulk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/projects/{project}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commits for a project with coding time */
        get: operations["getProjectCommits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/projects/{project}/commits/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single commit with coding time */
        get: operations["getProjectCommit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's organizations */
        get: operations["getOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/orgs/{org_id}/dashboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization dashboards */
        get: operations["getOrgDashboards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/orgs/{org_id}/dashboards/{dashboard_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dashboard members */
        get: operations["getOrgDashboardMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/orgs/{org_id}/dashboards/{dashboard_id}/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organization dashboard coding summaries */
        get: operations["getOrgDashboardSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all known editors */
        get: operations["getEditors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program_languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all known programming languages */
        get: operations["getProgramLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server metadata */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/{range}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate stats of all users */
        get: operations["getGlobalStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/data_dumps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List data exports */
        get: operations["getDataDumps"];
        put?: never;
        /** Start a data export */
        post: operations["createDataDump"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        OAuthProvider: "github" | "google" | "discord";
        User: {
            id: string;
            username: string;
            display_name?: string;
            /** Format: email */
            email?: string;
            /** Format: uri */
            photo?: string;
            bio?: string;
            city?: string;
            timezone?: string;
            /** Format: date-time */
            last_heartbeat_at?: string;
            last_project?: string;
            /** @enum {string} */
            plan?: "free" | "basic" | "premium";
            /** @description Keystroke timeout in minutes */
            timeout?: number;
            is_hireable?: boolean;
            github_username?: string;
            twitter_username?: string;
            /** Format: uri */
            website?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
        };
        PendingLink: {
            id: string;
            provider: components["schemas"]["OAuthProvider"];
            provider_username: string;
            provider_email: string;
            /** @description Username of the existing account to merge into */
            existing_username?: string;
            /** Format: date-time */
            expires_at: string;
        };
        LinkedProvider: {
            provider: components["schemas"]["OAuthProvider"];
            provider_user_id: string;
            provider_username: string;
            provider_email?: string;
            /** Format: date-time */
            created_at: string;
        };
        Project: {
            id: string;
            name: string;
            /** Format: uri */
            repository?: string;
            /** Format: uri */
            badge?: string;
            color?: string;
            has_public_url?: boolean;
            human_readable_last_heartbeat_at?: string;
            /** Format: date-time */
            last_heartbeat_at?: string;
            /** Format: date-time */
            first_heartbeat_at?: string;
            /** Format: uri */
            url?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @enum {string} */
        Category: "coding" | "building" | "indexing" | "debugging" | "browsing" | "running tests" | "writing tests" | "manual testing" | "writing docs" | "communicating" | "code reviewing" | "notes" | "researching" | "learning" | "designing" | "ai coding";
        HeartbeatInput: {
            /** @description File path, app name, or domain */
            entity: string;
            /** @enum {string} */
            type: "file" | "app" | "domain";
            /**
             * Format: double
             * @description UNIX epoch timestamp
             */
            time: number;
            category?: components["schemas"]["Category"];
            project?: string;
            project_root_count?: number;
            branch?: string;
            language?: string;
            /** @description Comma-separated dependency names */
            dependencies?: string;
            lines?: number;
            ai_line_changes?: number;
            human_line_changes?: number;
            lineno?: number;
            cursorpos?: number;
            is_write?: boolean;
            editor?: string;
            operating_system?: string;
        };
        Heartbeat: components["schemas"]["HeartbeatInput"] & {
            id: string;
            user_id: string;
            machine?: string;
            user_agent_id?: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        SummaryRange: "Today" | "Yesterday" | "Last 7 Days" | "Last 7 Days from Yesterday" | "Last 14 Days" | "Last 30 Days" | "This Week" | "Last Week" | "This Month" | "Last Month";
        GrandTotal: {
            /** Format: double */
            total_seconds: number;
            digital: string;
            text: string;
            hours?: number;
            minutes?: number;
        };
        SummaryItem: {
            name: string;
            /** Format: double */
            total_seconds: number;
            /** Format: double */
            percent: number;
            /** @description Digital clock format (H:MM) */
            digital: string;
            /** @description Human readable (e.g., '2 hrs 30 mins') */
            text: string;
            hours?: number;
            minutes?: number;
            seconds?: number;
        };
        TimeRange: {
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
            /** Format: date */
            date?: string;
            text?: string;
            timezone?: string;
        };
        Summary: {
            grand_total: components["schemas"]["GrandTotal"];
            categories?: components["schemas"]["SummaryItem"][];
            projects?: components["schemas"]["SummaryItem"][];
            languages?: components["schemas"]["SummaryItem"][];
            editors?: components["schemas"]["SummaryItem"][];
            operating_systems?: components["schemas"]["SummaryItem"][];
            dependencies?: components["schemas"]["SummaryItem"][];
            machines?: components["schemas"]["SummaryItem"][];
            branches?: components["schemas"]["SummaryItem"][];
            entities?: components["schemas"]["SummaryItem"][];
            range: components["schemas"]["TimeRange"];
        };
        CumulativeTotal: {
            /** Format: double */
            seconds?: number;
            text?: string;
            digital?: string;
        };
        DailyAverage: {
            /** Format: double */
            seconds?: number;
            text?: string;
        };
        Stats: {
            /** Format: double */
            total_seconds?: number;
            /** Format: double */
            total_seconds_including_other_language?: number;
            /** Format: double */
            daily_average?: number;
            /** Format: double */
            daily_average_including_other_language?: number;
            human_readable_total?: string;
            human_readable_total_including_other_language?: string;
            human_readable_daily_average?: string;
            human_readable_daily_average_including_other_language?: string;
            categories?: components["schemas"]["SummaryItem"][];
            projects?: components["schemas"]["SummaryItem"][];
            languages?: components["schemas"]["SummaryItem"][];
            editors?: components["schemas"]["SummaryItem"][];
            operating_systems?: components["schemas"]["SummaryItem"][];
            dependencies?: components["schemas"]["SummaryItem"][];
            machines?: components["schemas"]["SummaryItem"][];
            best_day?: {
                /** Format: date */
                date?: string;
                /** Format: double */
                total_seconds?: number;
                text?: string;
            };
            range?: components["schemas"]["TimeRange"];
            /** @enum {string} */
            status?: "ok" | "pending_update";
            is_already_updating?: boolean;
            is_up_to_date?: boolean;
        };
        AllTime: {
            /** Format: double */
            total_seconds: number;
            /** @description Human readable (e.g., '1,250 hrs 30 mins') */
            text: string;
            digital: string;
            is_up_to_date: boolean;
            range?: components["schemas"]["TimeRange"];
            project?: string;
        };
        Duration: {
            project: string;
            /**
             * Format: double
             * @description Start time as UNIX epoch
             */
            time: number;
            /**
             * Format: double
             * @description Duration in seconds
             */
            duration: number;
            color?: string;
            entity?: string;
            language?: string;
            branch?: string;
            category?: components["schemas"]["Category"];
            machine?: string;
        };
        Goal: {
            id: string;
            title: string;
            /** @enum {string} */
            type?: "coding" | "languages" | "editors" | "projects";
            /** @enum {string} */
            delta?: "day" | "week";
            /** Format: double */
            target_seconds?: number;
            is_enabled?: boolean;
            is_snoozed?: boolean;
            is_inverse?: boolean;
            languages?: string[];
            editors?: string[];
            projects?: string[];
            chart_data?: {
                /** Format: double */
                actual_seconds?: number;
                /** Format: double */
                goal_seconds?: number;
                range?: components["schemas"]["TimeRange"];
                /** @enum {string} */
                range_status?: "success" | "fail" | "pending";
            }[];
            /** @enum {string} */
            status?: "success" | "fail" | "pending";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
        };
        LeaderboardEntry: {
            rank?: number;
            user?: {
                id?: string;
                display_name?: string;
                username?: string;
                /** Format: uri */
                photo?: string;
                is_hireable?: boolean;
                city?: string;
                country_code?: string;
            };
            running_total?: {
                /** Format: double */
                total_seconds?: number;
                human_readable_total?: string;
                /** Format: double */
                daily_average?: number;
                human_readable_daily_average?: string;
                languages?: {
                    name?: string;
                    /** Format: double */
                    total_seconds?: number;
                }[];
            };
        };
        PrivateLeaderboard: {
            id: string;
            name: string;
            members_count?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
        };
        Insight: {
            type?: string;
            range?: components["schemas"]["TimeRange"];
            days?: {
                /** Format: date */
                date?: string;
                /** Format: double */
                total_seconds?: number;
                text?: string;
            }[];
            best_day?: {
                /** Format: date */
                date?: string;
                /** Format: double */
                total_seconds?: number;
                text?: string;
            };
            daily_average?: {
                /** Format: double */
                seconds?: number;
                text?: string;
            };
            items?: components["schemas"]["SummaryItem"][];
        };
        CustomRule: {
            id: string;
            /** @enum {string} */
            action: "change" | "delete";
            /** @enum {string} */
            source: "project" | "language" | "editor" | "operating_system" | "category" | "entity";
            /** @enum {string} */
            operation: "equals" | "contains" | "starts with" | "ends with";
            source_value: string;
            /** @enum {string} */
            destination: "project" | "language" | "editor" | "operating_system" | "category" | "entity";
            destination_value: string;
            priority?: number;
        };
        CustomRuleInput: {
            /** @description Include to update existing rule */
            id?: string;
            /** @enum {string} */
            action: "change" | "delete";
            /** @enum {string} */
            source: "project" | "language" | "editor" | "operating_system" | "category" | "entity";
            /** @enum {string} */
            operation: "equals" | "contains" | "starts with" | "ends with";
            source_value: string;
            /** @enum {string} */
            destination: "project" | "language" | "editor" | "operating_system" | "category" | "entity";
            destination_value: string;
            priority?: number;
        };
        Machine: {
            id: string;
            /** @description Machine hostname */
            value: string;
            ip?: string;
            /** Format: date-time */
            last_seen_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        UserAgent: {
            id: string;
            /** @description Full user agent string */
            value: string;
            editor?: string;
            version?: string;
            os?: string;
            is_browser_extension?: boolean;
            is_desktop_app?: boolean;
            /** Format: date-time */
            last_seen_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ExternalDurationInput: {
            external_id: string;
            entity: string;
            /** @enum {string} */
            type: "file" | "app" | "domain";
            /** Format: double */
            start_time: number;
            /** Format: double */
            end_time: number;
            category?: components["schemas"]["Category"];
            project?: string;
            branch?: string;
            language?: string;
            meta?: string;
        };
        ExternalDuration: components["schemas"]["ExternalDurationInput"] & {
            id: string;
            user_id: string;
            /** Format: date-time */
            created_at: string;
        };
        Commit: {
            hash: string;
            message: string;
            author_name?: string;
            /** Format: email */
            author_email?: string;
            /** Format: date-time */
            author_date: string;
            committer_name?: string;
            /** Format: email */
            committer_email?: string;
            /** Format: date-time */
            committer_date?: string;
            /** Format: double */
            total_seconds?: number;
            human_readable_total?: string;
            /** Format: uri */
            url?: string;
            ref?: string;
        };
        Organization: {
            id: string;
            name: string;
            timeout?: number;
            timezone?: string;
            writes_only?: boolean;
            /** @enum {string} */
            default_project_privacy?: "visible" | "hidden";
            is_duration_visible?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        OrgDashboard: {
            id: string;
            name: string;
            is_viewing_restricted?: boolean;
            is_manual_time_hidden?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        OrgMember: {
            id: string;
            user: components["schemas"]["User"];
            is_view_only?: boolean;
        };
        Editor: {
            id: string;
            name: string;
            color?: string;
            /** Format: uri */
            website?: string;
            /** Format: uri */
            repository?: string;
            latest_version?: string;
        };
        ProgramLanguage: {
            id: string;
            name: string;
            color?: string;
            is_verified?: boolean;
        };
        GlobalStats: {
            /** Format: double */
            total_seconds?: number;
            /** Format: double */
            total_seconds_including_other_language?: number;
            /** Format: double */
            daily_average?: number;
            human_readable_total?: string;
            human_readable_daily_average?: string;
            categories?: components["schemas"]["SummaryItem"][];
            languages?: components["schemas"]["SummaryItem"][];
            editors?: components["schemas"]["SummaryItem"][];
            operating_systems?: components["schemas"]["SummaryItem"][];
            range?: components["schemas"]["TimeRange"];
        };
        DataDump: {
            id: string;
            /** @enum {string} */
            type: "daily" | "heartbeats";
            /** @enum {string} */
            status: "pending" | "processing" | "completed" | "failed";
            /** Format: uri */
            download_url?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string;
        };
    };
    responses: {
        /** @description Authentication required or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Unauthorized */
                    error?: string;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Not found */
                    error?: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    oauthRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OAuth provider */
            302: {
                headers: {
                    Location?: string;
                    /** @description PKCE state and code_verifier stored in KV (TTL 10 min) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauthCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    /** @description Session cookie (HttpOnly, Secure, SameSite=Strict) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["User"];
                            /** @description API key for editor plugins (ck_...) */
                            api_key: string;
                            is_new_user?: boolean;
                            pending_link?: components["schemas"]["PendingLink"];
                        };
                    };
                };
            };
            /** @description Invalid OAuth callback (bad code/state) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    oauthLinkStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OAuth provider for linking */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    oauthLinkCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider linked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            provider: components["schemas"]["OAuthProvider"];
                            provider_username: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Provider account already linked to another user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    approvePendingLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pending_link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts merged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["User"];
                            api_key: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Pending link expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    getLinkedProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of linked providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LinkedProvider"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    unlinkProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider unlinked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot unlink last provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["User"];
                            providers?: components["schemas"]["LinkedProvider"][];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated */
            204: {
                headers: {
                    /** @description Clear session cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    regenerateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New API key generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            api_key: string;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username?: string;
                    display_name?: string;
                    bio?: string;
                    city?: string;
                    timezone?: string;
                    timeout?: number;
                    is_hireable?: boolean;
                    github_username?: string;
                    twitter_username?: string;
                    /** Format: uri */
                    website?: string;
                    /** Format: uri */
                    photo?: string;
                };
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    getProjects: {
        parameters: {
            query?: {
                /** @description Search term */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHeartbeats: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of heartbeats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Heartbeat"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatInput"];
            };
        };
        responses: {
            /** @description Heartbeat created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Heartbeat"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createHeartbeatsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatInput"][];
            };
        };
        responses: {
            /** @description Heartbeats accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        responses: [
                            components["schemas"]["Heartbeat"],
                            number
                        ][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteHeartbeatsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    date: string;
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description Heartbeats deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSummaries: {
        parameters: {
            query?: {
                /** @description Required if range is not provided. Use with end. */
                start?: string;
                /** @description Required if range is not provided. Use with start. */
                end?: string;
                /** @description Predefined range (alternative to start/end). One of start+end or range is required. */
                range?: components["schemas"]["SummaryRange"];
                project?: string;
                /** @description Comma-separated branch names */
                branches?: string;
                /** @description Keystroke timeout in minutes */
                timeout?: number;
                writes_only?: boolean;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Summary"][];
                        /** Format: date */
                        start?: string;
                        /** Format: date */
                        end?: string;
                        cumulative_total?: components["schemas"]["CumulativeTotal"];
                        daily_average?: components["schemas"]["DailyAverage"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getStats: {
        parameters: {
            query?: {
                timeout?: number;
                writes_only?: boolean;
            };
            header?: never;
            path: {
                range: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Stats"];
                    };
                };
            };
            /** @description Stats are still being calculated */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Stats"];
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getStatusBarToday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Today's status bar data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Summary"];
                        /** Format: date-time */
                        cached_at?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAllTimeSinceToday: {
        parameters: {
            query?: {
                project?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All time data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AllTime"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDurations: {
        parameters: {
            query: {
                date: string;
                project?: string;
                branches?: string;
                timeout?: number;
                writes_only?: boolean;
                timezone?: string;
                slice_by?: "project" | "entity" | "language" | "dependencies" | "operating_system" | "editor" | "category" | "machine";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of durations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Duration"][];
                        branches?: string[];
                        /** Format: date */
                        start?: string;
                        /** Format: date */
                        end?: string;
                        timezone?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of goals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Goal"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal with chart data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Goal"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPublicLeaders: {
        parameters: {
            query?: {
                language?: string;
                is_hireable?: boolean;
                country_code?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard rankings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        current_user?: components["schemas"]["LeaderboardEntry"];
                        data: components["schemas"]["LeaderboardEntry"][];
                        page?: number;
                        total_pages?: number;
                        range?: components["schemas"]["TimeRange"];
                        language?: string;
                        /** Format: date-time */
                        modified_at?: string;
                    };
                };
            };
        };
    };
    getPrivateLeaderboards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of private leaderboards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PrivateLeaderboard"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPrivateLeaderboard: {
        parameters: {
            query?: {
                language?: string;
                country_code?: string;
                page?: number;
            };
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard rankings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LeaderboardEntry"][];
                        page?: number;
                        total_pages?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getInsight: {
        parameters: {
            query?: {
                timeout?: number;
                writes_only?: boolean;
                /** @description Filter for 'days' insight type (0-6 or monday-sunday) */
                weekday?: string;
            };
            header?: never;
            path: {
                insight_type: "weekday" | "days" | "best_day" | "daily_average" | "projects" | "languages" | "editors" | "categories" | "machines" | "operating_systems";
                range: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insight data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Insight"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCustomRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of custom rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CustomRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCustomRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomRuleInput"][];
            };
        };
        responses: {
            /** @description Updated rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CustomRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMachineNames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of machines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Machine"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUserAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserAgent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getExternalDurations: {
        parameters: {
            query: {
                date: string;
                project?: string;
                branches?: string;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of external durations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ExternalDuration"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createExternalDuration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalDurationInput"];
            };
        };
        responses: {
            /** @description External duration created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ExternalDuration"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createExternalDurationsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalDurationInput"][];
            };
        };
        responses: {
            /** @description External durations created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ExternalDuration"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteExternalDurationsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    date: string;
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description External durations deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProjectCommits: {
        parameters: {
            query?: {
                author?: string;
                branch?: string;
                page?: number;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of commits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Commit"][];
                        page?: number;
                        total_pages?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProjectCommit: {
        parameters: {
            query?: {
                branch?: string;
            };
            header?: never;
            path: {
                project: string;
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commit data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Commit"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Organization"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrgDashboards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of dashboards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrgDashboard"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrgDashboardMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrgMember"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrgDashboardSummaries: {
        parameters: {
            query: {
                date: string;
                project?: string;
                branches?: string;
            };
            header?: never;
            path: {
                org_id: string;
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Summary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    getEditors: {
        parameters: {
            query?: {
                unreleased?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of editors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Editor"][];
                    };
                };
            };
        };
    };
    getProgramLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of languages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProgramLanguage"][];
                    };
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ip?: string;
                            version?: string;
                        };
                    };
                };
            };
        };
    };
    getGlobalStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                range: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GlobalStats"];
                    };
                };
            };
            /** @description Stats are still being calculated */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GlobalStats"];
                        message?: string;
                    };
                };
            };
        };
    };
    getDataDumps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of data dumps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DataDump"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDataDump: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "daily" | "heartbeats";
                    /** @default true */
                    email_when_finished?: boolean;
                };
            };
        };
        responses: {
            /** @description Export started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DataDump"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
